version: '3.8'  # Specify the Docker Compose file version

services:
  # Front End Service
  frontend:
    build:
      context: .  # Path to the front-end Dockerfile
      dockerfile: Dockerfile  # Dockerfile for the front-end
    ports:
      - "3000:80"  # Maps port 80 in the container to port 3000 on the host
    volumes:
      - ./frontend:/usr/share/nginx/html  # Mounts the frontend directory to the container

# Volumes for persistent data (if needed)
volumes:
  frontend_data:
